main:
  branches:
    get-image-metadata:
      branches:
        landsat:
          branches:
            point:
              arguments:
                latitude:
                  nargs: 2
                  action: store
                longitude:
                  nargs: 2
                  action: store
        sentinel:
          branches:
            point:
              arguments:
                latitude:
                  nargs: 2
                  action: store
                longitude:
                  nargs: 2
                  action: store
    config:
      branches:
        init:
          help: "Start initialization process."
          arguments:
            none:
              nargs: 0
              action:
                source: gxiba
                name: GxibaCLIActions.init
        reset:
          help: "Create or reset configuration file."
          arguments:
            none:
              nargs: 0
              action:
                source: gxiba
                name: GxibaCLIActions.reset_parameters
        set-parameter:
          help: "Set the value of a parameter by name."
          arguments:
            parameter-name:
              help: "Requires a valid parameter-name and new-value"
              nargs: 2
              action:
                source: gxiba
                name: GxibaCLIActions.set_parameter
        get-parameter:
          help: "Get the value of a parameter by name."
          arguments:
            parameter-name:
              help: "Requires a valid parameter-name."
              nargs: 1
              action:
                source: gxiba
                name: GxibaCLIActions.get_parameter
        get-description:
          help: "Get the description of a parameter by name."
          arguments:
            parameter-name:
              help: "Requires a valid parameter-name."
              nargs: 1
              action:
                source: gxiba
                name: GxibaCLIActions.get_description
        list-parameters:
          help: "Get a list of all available parameters."
          arguments:
            none:
              nargs: 0
              action:
                source: gxiba
                name: GxibaCLIActions.list_parameters
            --dont-print:
                nargs: 0
                action: store_true
        get-all-parameters:
          help: "Shows a list of all existing parameters and values."
          arguments:
            none:
              nargs: 0
              action:
                source: gxiba
                name: GxibaCLIActions.get_all_parameters
        error:
          help: "Raises an error."
          arguments:
            none:
              nargs: 0
              action:
                source: gxiba
                name: GxibaCLIActions.error

