logging-level:
  help: 'Logging level. Can be any of: DEBUG, INFO, WARNING, ERROR or CRITICAL'
  default: 'INFO'
logging-path:
  help: 'Path to log file.'
  default: '/tmp/gxiba_log.txt'
pg-user:
  help: 'Postgres database user.'
  default: 'postgres'
pg-password:
  help: 'Postgres database password.'
  default: ''
pg-address:
  help: 'Postgres database path.'
  default: 'localhost'
pg-port:
  help: 'Postgres database port.'
  default: '5432'
sentinel-2-bands:
  help: 'Sentinel band-name mapping'
  default:
    B01: 'coastal'
    B02: 'blue'
    B03: 'green'
    B04: 'red'
    B05: 'vegetation1'
    B06: 'vegetation2'
    B07: 'vegetation3'
    B08: 'nir'
    B09: 'water'
    B10: 'swircirrus'
    B11: 'swir2'
    B12: 'swir3'
landsat-8-bands:
  help: 'LandSat band name mapping'
  default:
    B1: 'coastal'
    B2: 'blue'
    B3: 'green'
    B4: 'red'
    B5: 'nir'
    B6: 'swir1'
    B7: 'swir2'
    B8: 'pan'
    B9: 'cirrus'
    B10: 'tirs1'
    B11: 'tirs2'
gs-bucket:
  help: 'Path to your gs-bucket'
  default: 'gs://gxiba-storage/'
keys-path:
  help: 'Path to Google service account keys.json file'
  default: '../keys.json'
