apiVersion: batch/v1
kind: CronJob
metadata:
  name: gxiba-sentinel-files-cron-update
spec:
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gxiba-update-files-sentinel
              image: alvaroubravo/gxiba:main
              imagePullPolicy: Always
              command: [ "python"]
              args: ["./examples/update_files.py", "--verbose", "--db-kind", "postgresql", "--db-host", "$(DB_HOST)", "--db-username", "$(DB_USERNAME)", "--db-password", "$(DB_PASSWORD)", "--db-port", "$(DB_PORT)", "--db-name", "$(DB_NAME)", "--bucket-path", "$(BUCKET_PATH)", "--get-keys-from-env", "--skip-landsat" ]
              envFrom:
              - secretRef:
                  name: google-service-account-keys
          restartPolicy: Never